<?php

/**
 * ProductsRepository
 *
 * @package EntityEcommerceBundle
 * @author Amal Hsouna
 */

namespace Entity\EcommerceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Entity\EcommerceBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your products
 * repository methods below.
 * @package EntityEcommerceBundle
 * @author  Amal Hsouna
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Finds all category.
     *
     * @return array
     */
    public function findAllCategory()
    {
        $category = $this->findAll();

        return $category;
    }

    /**
     * Persists category.
     *
     * @param Utilisateur $category The category model.
     *
     * @return void
     */
    public function saveCategory(Category $category)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($category);
        $entityManager->flush();
    }

    /**
     * delete category.
     *
     * @return true.
     */
    public function delete(Category $category)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->remove($category);
        $entityManager->flush();
    }

    /* Finds count product.
     * 
     * @return result
     */
    public function findCountCategory()
    {
        return $this->createQueryBuilder('c')
            ->select('COUNT(c)')
            ->getQuery()
            ->getSingleScalarResult();
    }

}
