<?php

/**
 * CustomerRepository
 * 
 * @package EntityEcommerceBundle
 * @author Amal Hsouna
 */

namespace Entity\EcommerceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Entity\EcommerceBundle\Entity\Customer;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your products
 * repository methods below.
 * @package EntityEcommerceBundle
 * @author  Amal Hsouna
 */
 
class CustomerRepository extends EntityRepository
{
    /**
     * Finds all Products.
     * 
     * @return array
     */
    public function findAllProducts()
    {
        $customer = $this->findAll();
        
        return $customer;
    }
    
       
    /**
     * Persists Customer.
     * 
     * @param Customer $customer The customer model.
     * 
     * @return void
     */
    public function save(Customer $customer)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($customer);
        $entityManager->flush();
    }
}