<?php

namespace Entity\EcommerceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartenaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaryRepository extends EntityRepository
{
}
