<?php

/**
 * PartenaryRepository
 * 
 * @package EntityEcommerceBundle
 * @author Amal Hsouna
 */

namespace Entity\EcommerceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Entity\EcommerceBundle\Entity\Partenary;

/**
 * PartenaryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenaryRepository extends EntityRepository
{
    /**
     * Persists Partenary.
     * 
     * @param Products $partenary The partenary model.
     * 
     * @return void
     */
    public function savePartenary(Partenary $partenary)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($partenary);
        $entityManager->flush();
    }
    
    /**
     * Finds all Partenary.
     * 
     * @return array
     */
    public function findAllPartenary()
    {
        $listPartenary = $this->findAll();
        
        return $listPartenary;
    }
}
