<?php

/**
 * ProductsRepository
 * 
 * @package EntityEcommerceBundle
 * @author Amal Hsouna
 */

namespace Entity\EcommerceBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Entity\EcommerceBundle\Entity\Products;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your products
 * repository methods below.
 * @package EntityEcommerceBundle
 * @author  Amal Hsouna
 */
 
class ProductsRepository extends EntityRepository
{
    /**
     * Finds all Products.
     * 
     * @return array
     */
    public function findAllProducts()
    {
        $numeros = $this->findAll();
        
        return $numeros;
    }
    
       
    /**
     * Persists products.
     * 
     * @param Products $products The products model.
     * 
     * @return void
     */
    public function saveProducts(Products $products)
    {
        $entityManager = $this->getEntityManager();
        $entityManager->persist($products);
        $entityManager->flush();
    }
    
    /**
     * Finds Products by id.
     * 
     * @return array
     */
    public function findProductsById($id)
    {
        $products = $this->findById($id);

        return $products;
    }
}