front_customer:
    resource: "@frontCustomerBundle/Resources/config/routing.yml"
    prefix:   /

back_utilisateur:
    resource: "@backAdminBundle/Resources/config/routing.yml"
    prefix:   /

back_product:
    resource: "@backProductBundle/Resources/config/routing.yml"
    prefix:   /

front_home:
    resource: "@frontHomeBundle/Resources/config/routing.yml"
    prefix:   /
    
back_home:
    resource: "@backHomeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@backAdminBundle/Resources/config/routing.yml"
