back_utilisateur:
    resource: "@backUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

back_product:
    resource: "@backProductBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
