#customer
front_customer_login_page:
    path:     /connexion
    defaults: { _controller: frontCustomerBundle:Customer:index }
    requirements:
       _method: GET
       
front_customer_my_compte_page:
    path:     /mon-compte
    defaults: { _controller: frontCustomerBundle:Customer:myCompte }
    requirements:
       _method: GET
       
front_customer_my_orders_page:
    path:     /mes-coupons/{customer}
    defaults: { _controller: frontCustomerBundle:Customer:myOrders }
    requirements:
        customer:  \d+  

#register customer
front_customer_register_page:
    path:     /inscription
    defaults: { _controller: frontCustomerBundle:Customer:postRegisterCustomer }
    
#detail customer
front_customer_detail_page:
    path:     /profile
    defaults: { _controller: frontCustomerBundle:Customer:getInfoCustomer }
    
