#category routing 
#list of category
back_category_list_category:
    path:     /liste-categorie
    defaults: { _controller: backProductBundle:Category:getListCategory }
    requirements:
       _method: GET
    
#Add category by admin
back_category_admin_add_category:
    path:     /ajouter-categorie
    defaults: { _controller: backProductBundle:Category:postCategory }
    
#Update category by admin
back_category_admin_update_category:
    path:     /modifier-categorie/{id}
    defaults: { _controller: backProductBundle:Category:putCategory }
    
#delete category by admin
back_category_admin_delete_category:
    path:     /espace-admin/{id}/categorie
    defaults: { _controller: backProductBundle:Category:deleteProducts }
    
#Add products
back_product_admin_add_sub_category:
    path:     /ajouter-sousCategorie
    defaults: { _controller: backProductBundle:Category:postSubCategory }