parameters:
    back_product.products.form.class: Symfony\Component\Form\Form
    
    back_product.products.form.type.class: back\ProductBundle\Form\Type\AddProductsFormType
    back_product.products.form_data_class:  Entity\EcommerceBundle\Entity\Products
     
    back_product.images.form.type.class: back\ProductBundle\Form\Type\ImagesFormType
    back_product.images.form_data_class: Entity\EcommerceBundle\Entity\Images
    
    #handler
    back_product.add.handler.client.class: back\ProductBundle\Form\Handler\AddProductsFormHandler
    back_product.update.handler.client.class: back\ProductBundle\Form\Handler\AddProductsFormHandler
    
services:
    back_product.products.form:
        class: %back_product.products.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - "create_products"
            - "@back_product.products.form.type"
            - ~
            
    back_product.images.form.type:
        class: %back_product.images.form.type.class%
        arguments: [%back_product.images.form_data_class%]
           
    back_product.products.form.type:
        class: %back_product.products.form.type.class%
        arguments: [%back_product.products.form_data_class%, "@back_product.images.form.type"]
            
    back_product.handler.add.products:
        class: %back_product.add.handler.client.class%
        arguments: ["@doctrine", "@back_product.products.form", "@back_product.manager.products"]
        
    back_product.handler.update.products:
        class: %back_product.update.handler.client.class%
        arguments: ["@doctrine", "@back_product.products.form", "@back_product.manager.products"]
        


