parameters:
    back_product.products.form.class: Symfony\Component\Form\Form
    
    back_product.products.form.type.class: back\ProductBundle\Form\Type\AddProductsFormType
    back_product.products.form_data_class:  Entity\EcommerceBundle\Entity\Products
     
    back_product.images.form.type.class: back\ProductBundle\Form\Type\ImagesFormType
    back_product.images.form_data_class: Entity\EcommerceBundle\Entity\Images
    
    back_product.category.form.type.class: back\ProductBundle\Form\Type\AddCategoryFormType
    back_product.category.form_data_class: Entity\EcommerceBundle\Entity\Category
    
    back_product.partenary.form.type.class: back\ProductBundle\Form\Type\PartenaryFormType
    back_product.partenary.form_data_class: Entity\EcommerceBundle\Entity\Partenary
    
    back_product.sub.category.form.type.class: back\ProductBundle\Form\Type\AddSubCategoryFormType
    back_product.sub.category.form_data_class: Entity\EcommerceBundle\Entity\SubCategory
    
    back_product.ckeditor.form.type.class: back\ProductBundle\Form\Type\CkeditorFormType
    
    #handler
    back_product.add.handler.client.class: back\ProductBundle\Form\Handler\AddProductsFormHandler
    back_product.update.handler.client.class: back\ProductBundle\Form\Handler\UpdateProductsFormHandler
    back_product.add.category.handler.client.class: back\ProductBundle\Form\Handler\AddCategoryFormHandler
    back_product.update.category.handler.client.class: back\ProductBundle\Form\Handler\UpdateCategoryFormHandler
    back_product.add.partenary.handler.client.class: back\ProductBundle\Form\Handler\AddPartenaryFormHandler
    back_product.update.partenary.handler.client.class: back\ProductBundle\Form\Handler\UpdatePartenaryFormHandler
    back_product.add.sub.category.handler.client.class: back\ProductBundle\Form\Handler\AddSubCategoryFormHandler
    
    
services:
    #tags
    back_product.ckeditor:
        class: %back_product.ckeditor.form.type.class%
        tags:
            - { name: form.type, alias: ckeditor }
            
    #add products
    back_product.products.form:
        class: %back_product.products.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - "create_products"
            - "@back_product.products.form.type"
            - ~
            
    back_product.images.form.type:
        class: %back_product.images.form.type.class%
        arguments: [%back_product.images.form_data_class%]
        
    back_product.partenary.form.type:
        class: %back_product.partenary.form.type.class%
        arguments: [%back_product.partenary.form_data_class%]
    
    back_product.sub.category.form.type:
        class: %back_product.sub.category.form.type.class%
        arguments: [%back_product.sub.category.form_data_class%]
        
    back_product.update.partenary.form.type:
        class: %back_product.partenary.form.type.class%
        arguments: 
             - %back_product.partenary.form_data_class%
             - "PUT"
           
    back_product.products.form.type:
        class: %back_product.products.form.type.class%
        arguments: [%back_product.products.form_data_class%, "@back_product.images.form.type", "@back_product.category.form.type", "@back_product.ckeditor", "@back_product.partenary.form.type"]
             
    back_product.category.form.type:
        class: %back_product.category.form.type.class%
        arguments: 
        - %back_product.category.form_data_class%
        
    back_product.handler.add.products:
        class: %back_product.add.handler.client.class%
        arguments: ["@back_product.products.form", "@back_product.manager.products"]
        
    back_product.handler.update.products:
        class: %back_product.update.handler.client.class%
        arguments: ["@back_product.products.form", "@back_product.manager.products"]
    
    #add and update category
    back_product.category.form:
        class: %back_product.category.form.type.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - ~
            - "@back_product.category.form.type"
            - ~
            
    #add sub category
    back_product.sub.category.form:
        class: %back_product.sub.category.form.type.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - ~
            - "@back_product.sub.category.form.type"
            - ~
        
    back_product.handler.add.category:
        class: %back_product.add.category.handler.client.class%
        arguments: ["@back_product.category.form", "@back_product.manager.category"]  
    
    #update category form type
    back_product.handler.update.category:
        class: %back_product.update.category.handler.client.class%
        arguments: ["@back_product.category.form", "@back_product.manager.category"]  
        
    #add and update partenary
    back_product.partenary.form:
        class: %back_product.partenary.form.type.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - ~
            - "@back_product.partenary.form.type"
            
            
    back_product.handler.add.partenary:
        class: %back_product.add.partenary.handler.client.class%
        arguments: ["@back_product.partenary.form", "@back_product.manager.products"]  
        
    back_product.handler.update.partenary:
        class: %back_product.update.partenary.handler.client.class%
        arguments: ["@back_product.partenary.form", "@back_product.manager.products"]  
        
    back_product.handler.add.sub.category:
        class: %back_product.add.sub.category.handler.client.class%
        arguments: ["@back_product.sub.category.form", "@back_product.manager.category"]  
   
