product:
  resource: "@backProductBundle/Resources/config/product.yml"
  prefix: /espace-admin
  
category:
  resource: "@backProductBundle/Resources/config/category.yml"
  prefix: /espace-admin
  
partenary:
  resource: "@backProductBundle/Resources/config/partenary.yml"
  prefix: /espace-admin
  
#delete products
back_product_admin_end_date_products:
    path:     /dealspasses
    defaults: { _controller: backProductBundle:Products:getProductsByEndDate }
    
##partenary
