product:
  resource: "@backProductBundle/Resources/config/product.yml"
  prefix: /espace-admin
  
category:
  resource: "@backProductBundle/Resources/config/category.yml"
  prefix: /espace-admin
  
partenary:
  resource: "@backProductBundle/Resources/config/partenary.yml"
  prefix: /espace-admin
  
#delete products
back_product_admin_end_date_products:
    path:     /dealspasses
    defaults: { _controller: backProductBundle:Products:getProductsByEndDate }
    
##partenary
#Add partenary
back_product_admin_add_partenary:
    path:     /espace-admin/ajouter-partenaire
    defaults: { _controller: backProductBundle:Products:postPartenary }
    
#list partenary
back_product_admin_list_partenary:
    path:     /espace-admin/list-partenaire
    defaults: { _controller: backProductBundle:Products:getListPartenary }
    
#detail partenary
back_product_admin_detail_partenary:
    path:     /espace-admin/{id}/detail-partenaire
    defaults: { _controller: backProductBundle:Products:getDetailPartenaryAdmin }
    
#update partenary
back_product_admin_update_partenary:
    path:     /espace-admin/{id}/modifier-partenaire
    defaults: { _controller: backProductBundle:Products:updatePartenaryAdmin }