product:
  resource: "@backProductBundle/Resources/config/product.yml"
  prefix: /espace-admin
  
category:
  resource: "@backProductBundle/Resources/config/category.yml"
  prefix: /espace-admin
  
#delete products
back_product_admin_end_date_products:
    path:     /dealspasses
    defaults: { _controller: backProductBundle:Products:getProductsByEndDate }
    
#category routing 
#list of category
back_category_list_category:
    path:     /liste-categorie
    defaults: { _controller: backProductBundle:Category:getListCategory }
    requirements:
       _method: GET
    
#Add category by admin
back_category_admin_add_category:
    path:     /ajouter-category
    defaults: { _controller: backProductBundle:Category:postCategory }
    
#Update category by admin
back_category_admin_update_category:
    path:     /modifier-category/{id}
    defaults: { _controller: backProductBundle:Category:putCategory }
    
#delete category by admin
back_category_admin_delete_category:
    path:     /espace-admin/{id}/category
    defaults: { _controller: backProductBundle:Category:deleteProducts }

##partenary
#Add partenary
back_product_admin_add_partenary:
    path:     /espace-admin/ajouter-partenaire
    defaults: { _controller: backProductBundle:Products:postPartenary }
    
#list partenary
back_product_admin_list_partenary:
    path:     /espace-admin/list-partenaire
    defaults: { _controller: backProductBundle:Products:getListPartenary }
    
#detail partenary
back_product_admin_detail_partenary:
    path:     /espace-admin/{id}/detail-partenaire
    defaults: { _controller: backProductBundle:Products:getDetailPartenaryAdmin }
    
#update partenary
back_product_admin_update_partenary:
    path:     /espace-admin/{id}/modifier-partenaire
    defaults: { _controller: backProductBundle:Products:updatePartenaryAdmin }