#Add products
back_product_admin_add_products:
    path:     /espace-admin/ajouter-produits
    defaults: { _controller: backProductBundle:Products:postProducts }
    
#Update products 
back_product_admin_put_products:
    path:     /espace-admin/modifier-produits/{id}
    defaults: { _controller: backProductBundle:Products:putProducts }
    requirements:
       id: \d+
       
#list products by admin
back_product_admin_list_products:
    path:     /espace-admin/list-produits
    defaults: { _controller: backProductBundle:Products:getProducts }
    
#details products
back_product_admin_details_products:
    path:     /espace-admin/{id}/details-produits
    defaults: { _controller: backProductBundle:Products:getDetailsProductsAdmin }
    
#delete products
back_product_admin_delete_products:
    path:     /espace-admin/{id}/delete-produits
    defaults: { _controller: backProductBundle:Products:deleteProducts }
    
#category routing 
#list of category
back_category_list_category:
    path:     /liste/category
    defaults: { _controller: backProductBundle:Category:getListCategory }
    requirements:
       _method: GET
    
#Add category by admin
back_category_admin_add_category:
    path:     /ajouter/category
    defaults: { _controller: backProductBundle:Category:postCategory }
    
#delete category by admin
back_category_admin_delete_category:
    path:     /espace-admin/{id}/category
    defaults: { _controller: backProductBundle:Category:deleteProducts }
