parameters:
    product.manager.client.class: back\ProductBundle\ModelManager\ProductManger
    category.manager.client.class: back\ProductBundle\ModelManager\CategoryManger
    
services:
    back_product.manager.products:
        class: %product.manager.client.class%
        arguments: ["@doctrine"]
        
    back_product.manager.category:
        class: %category.manager.client.class%
        arguments: ["@doctrine"]
        
