<?php

/**
 * CustomerRepository.
 * 
 * @author Amal Hsouna
 */

namespace back\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your products
 * repository methods below.
 *
 * @author  Amal Hsouna
 */
class UserRepository extends EntityRepository
{
    /**
     * Finds Products with the date has passed.
     * 
     * @return array
     */
    public function findUserByDate()
    {
        $query = $this->_em->createQuery('SELECT u FROM backAdminBundle:User u where u.lastLogin > :token')
                      ->setMaxResults(1)->setParameter('token', '04/06/2016');
        $resultsQuery = $query->getResult();

        return $resultsQuery;
    }

    /* Finds count Partenary.
     * 
     * @return result
     */
    public function findCountUser()
    {
        return $this->createQueryBuilder('u')
                    ->select('COUNT(u)')
                    ->getQuery()
                    ->getSingleScalarResult();
    }
}
