parameters:
    back_utilisateur.manager.client.class: back\AdminBundle\ModelManager\UserManager
    
services:
    back_utilisateur.manager.client:
        class: %back_utilisateur.manager.client.class%
        arguments: ["@doctrine"]
