parameters:
    
    front_product.products.form.class: Symfony\Component\Form\Form
    
    front_product.contact.form.type.class: front\HomeBundle\Form\Type\ContactFormType
    front_product.contact.form_data_class:  Entity\EcommerceBundle\Entity\Contact
    
    front_product.search.form.type.class: front\HomeBundle\Form\Type\SearchCityFormType
    
    front_product.contact.handler.client.class: front\HomeBundle\Form\Handler\ContactFormHandler
    
services:
    
    front_product.search.product.form.type:
        class: %front_product.search.form.type.class%
        
    #search products
    front_product.products.form:
        class: %front_product.products.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - ~
            - "@front_product.search.product.form.type"
            
    front_product.contact.customer.form.type:
        class: %front_product.contact.form.type.class%
        arguement: [%front_product.contact.form_data_class%]
    
     #search products
    front_product.contact.form:
        class: %front_product.products.form.class%
        factory_service: form.factory
        factory_method: createNamed
        arguments:
            - ~
            - "@front_product.contact.customer.form.type"
            
    front_product.handler.contact.products:
        class: %front_product.contact.handler.client.class%
        argument: ["@front_product.contact.form", "@front_home.manager.mail"]
        
        
