#page acceuil
front_home_homepage:
    path:     /
    defaults: { _controller: frontHomeBundle:Home:index }
    requirements:
       _method: GET
       
#contact page
front_home_contact_page:
    path:     /contact
    defaults: { _controller: frontHomeBundle:Home:contact }

#detail products page
front_home_detail_products:
    path:     /detail/{id}/product
    defaults: { _controller: frontHomeBundle:Home:getDetailsProducts }
 
#####pannier####
#info panier
front_customer_mon_pannier_page:
    path:     /mon-pannier
    defaults: { _controller: frontHomeBundle:Pannier:pannierCustomer } 
    
#add of panier
front_customer_add_pannier_page:
    path:     /{id}/ajouter-pannier
    defaults: { _controller: frontHomeBundle:Pannier:addPannier }   
    
#delete panier
front_customer_delete_pannier_page:
    path:     /{id}/supprimer-pannier
    defaults: { _controller: frontHomeBundle:Pannier:deletePannierCustomer }     
    

