parameters:
    home.manager.client.class: front\HomeBundle\ModelManager\HomeManager

services:
    front_home.manager.home:
        class: %home.manager.client.class%
        arguments: ["@doctrine"]
